### ISSUE TITLE
最后加点文档。。。

### ISSUE THREAD

**Issue by elseyu** [easonlius/fingercode#1]
比如环境配置、程序架构、如何能最快跑起来、还有点注释、、、、

**Comment by easonlius** [comment]
已经添加了

**Comment by easonlius** [comment]
已经添加了。

**Comment by easonlius** [comment]
已经添加了，readme_CN里面

**Comment by elseyu** [comment]
你的paper连接打不开

**Comment by elseyu** [comment]
paper的打开了，但是open cv的404

**Comment by easonlius** [comment]
我已经修好opencv得那个链接了，至于paper得那个，全称是FingerCode： A Filterbank for Fingerprint Representation and Matching
